name: melanoma-artifacts
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip
  - pip:
      - numpy==1.26.4
      - pandas==2.2.2
      - scikit-learn==1.5.2
      - matplotlib==3.9.0
      - seaborn==0.13.2
      - opencv-python==4.10.0.84
      - tqdm==4.66.4
      - pillow==10.3.0
      - einops==0.8.0
      - albumentations==1.4.8
      - torchmetrics==1.4.0
